/**
 * Name lists copied from the app's code catalogs (src/domain/dishes.ts
 * DISH_CATALOG, src/domain/tags.ts TAG_CATALOG). The backend never renders
 * dishes or tags — it only needs the NAMES so `isCodeCatalogName` can skip
 * capturing offerings the code already ships. Kept in sync by the STANDING RULE.
 */

/** Every dish name in the app's DISH_CATALOG (src/domain/dishes.ts). */
export const DISH_NAMES: string[] = [
  // appetizers
  'Paneer Tikka', 'Paneer 65', 'Chilli Paneer', 'Malai Paneer Tikka',
  'Achari Paneer Tikka', 'Hara Bhara Kabab', 'Dahi Ke Kebab', 'Crispy Corn',
  'Honey Chilli Potato', 'Veg Manchurian Dry', 'Chilli Mushroom',
  'Mushroom Tikka', 'Soya Chaap Tikka', 'Malai Chaap', 'Veg Spring Roll',
  'Samosa', 'Aloo Tikki', 'Onion Pakoda', 'Paneer Pakoda', 'Cheese Balls',
  'French Fries', 'Peri Peri Fries', 'Cheesy Nachos', 'Chicken Tikka',
  'Chicken Malai Tikka', 'Tandoori Chicken', 'Chicken 65', 'Chilli Chicken',
  'Chicken Lollipop', 'Chicken Seekh Kebab', 'Chicken Wings',
  'Mutton Seekh Kebab', 'Mutton Galouti Kebab', 'Fish Tikka', 'Fish Fry',
  'Prawn Koliwada', 'Egg Chilli', 'Chicken Spring Roll',
  // soups
  'Tomato Soup', 'Sweet Corn Soup', 'Veg Manchow Soup', 'Hot and Sour Soup',
  'Veg Clear Soup', 'Lemon Coriander Soup', 'Cream of Mushroom Soup',
  'Cream of Tomato Soup', 'Spinach Soup', 'Chicken Manchow Soup',
  'Chicken Hot and Sour Soup', 'Chicken Sweet Corn Soup', 'Chicken Clear Soup',
  'Mutton Shorba',
  // salads
  'Green Salad', 'Kachumber Salad', 'Onion Salad', 'Russian Salad',
  'Caesar Salad', 'Greek Salad', 'Sprouts Salad', 'Corn Chaat', 'Fruit Salad',
  'Coleslaw', 'Chicken Caesar Salad', 'Tandoori Chicken Salad',
  // main course
  'Paneer Butter Masala', 'Shahi Paneer', 'Kadai Paneer', 'Palak Paneer',
  'Matar Paneer', 'Paneer Lababdar', 'Paneer Bhurji', 'Paneer Do Pyaza',
  'Chilli Paneer Gravy', 'Malai Kofta', 'Veg Kofta', 'Dal Makhani',
  'Dal Tadka', 'Dal Fry', 'Chana Masala', 'Rajma Masala', 'Aloo Gobi',
  'Bhindi Masala', 'Baingan Bharta', 'Mix Veg', 'Veg Kolhapuri',
  'Veg Jalfrezi', 'Kaju Curry', 'Mushroom Masala', 'Soya Chaap Masala',
  'Veg Manchurian Gravy', 'Sarson Ka Saag', 'Navratan Korma',
  'Methi Malai Matar', 'Dum Aloo', 'Butter Chicken', 'Chicken Tikka Masala',
  'Kadai Chicken', 'Chicken Curry', 'Chicken Handi', 'Chicken Korma',
  'Chicken Chettinad', 'Murgh Musallam', 'Mutton Rogan Josh', 'Mutton Curry',
  'Mutton Handi', 'Mutton Keema', 'Fish Curry', 'Egg Curry', 'Prawn Masala',
  // breads
  'Tandoori Roti', 'Butter Roti', 'Naan', 'Butter Naan', 'Garlic Naan',
  'Cheese Naan', 'Cheese Garlic Naan', 'Stuffed Kulcha', 'Amritsari Kulcha',
  'Lachha Paratha', 'Pudina Paratha', 'Aloo Paratha', 'Paneer Paratha',
  'Missi Roti', 'Rumali Roti', 'Bhatura', 'Poori', 'Chapati',
  // rice
  'Steamed Rice', 'Jeera Rice', 'Veg Pulao', 'Veg Biryani',
  'Hyderabadi Veg Biryani', 'Paneer Biryani', 'Veg Fried Rice',
  'Schezwan Fried Rice', 'Burnt Garlic Fried Rice', 'Curd Rice', 'Lemon Rice',
  'Kashmiri Pulao', 'Dal Khichdi', 'Chicken Biryani',
  'Hyderabadi Chicken Dum Biryani', 'Mutton Biryani', 'Egg Biryani',
  'Chicken Fried Rice', 'Egg Fried Rice',
  // noodles
  'Veg Hakka Noodles', 'Veg Chowmein', 'Schezwan Noodles',
  'Chilli Garlic Noodles', 'Singapore Noodles', 'Pan Fried Noodles',
  'Veg Chopsuey', 'Paneer Chilli Noodles', 'Chicken Hakka Noodles',
  'Chicken Chowmein', 'Chicken Schezwan Noodles', 'Egg Noodles',
  'Mixed Non-veg Noodles',
  // pasta
  'White Sauce Pasta', 'Red Sauce Pasta', 'Pink Sauce Pasta', 'Alfredo Pasta',
  'Arrabbiata Pasta', 'Pesto Pasta', 'Mac and Cheese', 'Veg Lasagna',
  'Spaghetti Aglio e Olio', 'Chicken Alfredo Pasta', 'Spaghetti Bolognese',
  'Chicken Lasagna',
  // pizza
  'Margherita Pizza', 'Farmhouse Pizza', 'Corn and Cheese Pizza',
  'Paneer Tikka Pizza', 'Veggie Delight Pizza', 'Cheese Burst Pizza',
  'Double Cheese Pizza', 'Mexican Green Wave Pizza', 'Tandoori Paneer Pizza',
  'Garlic Bread', 'Cheesy Garlic Bread', 'Chicken Tikka Pizza',
  'Chicken Pepperoni Pizza', 'BBQ Chicken Pizza', 'Chicken Supreme Pizza',
  // burger
  'Veg Burger', 'Aloo Tikki Burger', 'Cheese Burger', 'Paneer Burger',
  'Crispy Veg Burger', 'Mexican Burger', 'Chicken Burger',
  'Crispy Chicken Burger', 'Chicken Cheese Burger', 'Egg Burger',
  // sandwich
  'Veg Sandwich', 'Grilled Veg Sandwich', 'Bombay Masala Sandwich',
  'Cheese Sandwich', 'Cheese Corn Sandwich', 'Paneer Tikka Sandwich',
  'Club Sandwich', 'Chicken Sandwich', 'Grilled Chicken Sandwich',
  'Chicken Tikka Sandwich', 'Egg Sandwich',
  // desserts
  'Gulab Jamun', 'Rasmalai', 'Rasgulla', 'Gajar Ka Halwa', 'Moong Dal Halwa',
  'Jalebi', 'Kheer', 'Rabri', 'Kulfi', 'Falooda', 'Shahi Tukda', 'Malpua',
  'Ice Cream', 'Brownie with Ice Cream', 'Sizzling Brownie',
  'Chocolate Lava Cake', 'Cheesecake', 'Tiramisu', 'Fruit Custard',
  'Gulab Jamun with Ice Cream',
  // beverages — tea
  'Masala Chai', 'Adrak Chai', 'Elaichi Chai', 'Kadak Chai', 'Green Tea',
  'Lemon Tea', 'Black Tea', 'Honey Lemon Tea', 'Tandoori Chai',
  'Kashmiri Kahwa', 'Iced Tea', 'Peach Iced Tea',
  // beverages — coffee
  'Filter Coffee', 'Hot Coffee', 'Cold Coffee', 'Cold Coffee with Ice Cream',
  'Espresso', 'Americano', 'Cappuccino', 'Latte', 'Flat White', 'Mocha',
  'Caramel Macchiato', 'Affogato', 'Frappe',
  // beverages — shakes
  'Mango Shake', 'Banana Shake', 'Chocolate Shake', 'Vanilla Shake',
  'Strawberry Shake', 'Oreo Shake', 'KitKat Shake', 'Butterscotch Shake',
  'Dry Fruit Shake', 'Mango Lassi', 'Sweet Lassi', 'Salted Lassi', 'Chaas',
  // beverages — fresh juice
  'Orange Juice', 'Mosambi Juice', 'Pineapple Juice', 'Watermelon Juice',
  'Pomegranate Juice', 'Mixed Fruit Juice', 'Sugarcane Juice', 'ABC Juice',
  'Nimbu Pani',
  // beverages — soft drinks
  'Coke', 'Pepsi', 'Sprite', 'Fanta', 'Thums Up', 'Limca', 'Maaza',
  'Mineral Water', 'Soda', 'Red Bull',
  // beverages — mocktails
  'Virgin Mojito', 'Blue Lagoon', 'Fruit Punch', 'Green Apple Mojito',
  'Watermelon Mojito', 'Virgin Pina Colada', 'Cranberry Cooler', 'Jal Jeera',
  'Aam Panna',
  // beverages — cocktails
  'Mojito', 'Margarita', 'Long Island Iced Tea', 'Cosmopolitan', 'Bloody Mary',
  'Whiskey Sour', 'Old Fashioned', 'Pina Colada', 'Screwdriver', 'Sangria',
  'Beer Tower',
];

/** The curated business-tag vocabulary (src/domain/tags.ts TAG_CATALOG). */
export const TAG_NAMES: string[] = [
  'Restaurant', 'Cafe', 'Bakery', 'Sweet Shop', 'Tea Stall', 'Coffee',
  'Juice Shop', 'Ice Cream', 'Fast Food', 'Street Food', 'Chaat', 'Momos',
  'Rolls & Shawarma', 'Pizza', 'Burger', 'Biryani', 'Chinese',
  'South Indian', 'North Indian', 'Thali', 'Dhaba', 'Pure Veg', 'Non-Veg',
  'Seafood', 'Desserts', 'Cakes', 'Snacks', 'Breakfast', 'Family Dining',
  'Fine Dining', 'Buffet', 'Takeaway', 'Home Delivery', 'Cloud Kitchen',
  'Catering', 'Tiffin Service', 'Mess', 'Paan Shop',
  'Grocery', 'Kirana Store', 'General Store', 'Supermarket',
  'Vegetables & Fruits', 'Dairy', 'Milk Dairy', 'Meat Shop',
  'Chicken & Mutton', 'Fish Market', 'Eggs', 'Masala & Spices', 'Dry Fruits',
  'Organic Store', 'Flour Mill',
  'Medical Store', 'Pharmacy', 'Electronics', 'Mobile Shop', 'Computer Shop',
  'Home Appliances', 'Camera Shop', 'Fashion', 'Clothing', 'Menswear',
  'Womenswear', 'Kidswear', 'Sarees', 'Ethnic Wear', 'Boutique', 'Footwear',
  'Bags & Luggage', 'Watches', 'Opticals', 'Jewelry', 'Artificial Jewellery',
  'Furniture', 'Home Decor', 'Kitchenware', 'Crockery & Utensils', 'Hardware',
  'Paint Store', 'Electrical Shop', 'Sanitaryware', 'Tiles & Marble',
  'Building Material', 'Stationery', 'Books', 'Toys', 'Gifts', 'Florist',
  'Plant Nursery', 'Pet Shop', 'Aquarium', 'Handicrafts', 'Handmade',
  'Art Supplies', 'Sports Goods', 'Cycle Store', 'Musical Instruments',
  'Puja Store', 'Second Hand', 'Scrap Dealer',
  'Electrician', 'Plumber', 'Painter', 'Carpenter', 'Mason',
  'Welder & Fabricator', 'House Cleaning', 'Deep Cleaning',
  'Sofa & Carpet Cleaning', 'Water Tank Cleaning', 'Pest Control',
  'AC Repair', 'AC Installation', 'Fridge Repair', 'Washing Machine Repair',
  'TV Repair', 'Appliance Repair', 'RO & Water Purifier', 'Geyser Repair',
  'Inverter & Battery', 'Solar Installation', 'CCTV Installation',
  'Home Repair', 'Waterproofing', 'False Ceiling', 'Modular Kitchen',
  'Interior Designer', 'Architect', 'Borewell', 'Water Supply', 'Gardener',
  'Landscaping', 'Locksmith', 'Glass & Aluminium', 'Curtains & Blinds',
  'Maid Service', 'Cook at Home', 'Babysitter', 'Elder Care',
  'Security Service', 'Pool Service', 'Laundry', 'Dry Cleaning', 'Ironing',
  'Milk Delivery', 'Newspaper Delivery',
  'Mechanic', 'Car Repair', 'Bike Repair', 'Auto Garage', 'Tyres',
  'Wheel Alignment', 'Vehicle Service', 'Car Wash', 'Car Detailing',
  'Denting & Painting', 'Car AC', 'Battery Shop', 'Spare Parts',
  'Car Accessories', 'Bike Accessories', 'Puncture Repair', 'Towing',
  'Taxi', 'Auto Rickshaw', 'Transport', 'Truck', 'Tempo Service',
  'Packers & Movers', 'Courier', 'Logistics', 'School Bus Service',
  'Bus Service', 'Driving School', 'RTO Agent', 'Car Dealer', 'Bike Dealer',
  'Used Vehicles', 'EV Charging',
  'Salon', "Men's Salon", 'Ladies Salon', 'Haircut', 'Beauty Parlour', 'Spa',
  'Massage', 'Makeup Artist', 'Bridal Makeup', 'Nail Art', 'Tattoo',
  'Piercing', 'Gym', 'Fitness', 'Yoga', 'Zumba', 'Personal Trainer',
  'Dietician',
  'Doctor', 'Clinic', 'Hospital', 'Dentist', 'Physiotherapy',
  'Pathology Lab', 'Diagnostics', 'Eye Clinic', 'Skin Clinic', 'Homeopathy',
  'Ayurveda', 'Counselling', 'Veterinary', 'Pet Grooming', 'Ambulance',
  'Hearing Aids',
  'Tutor', 'Home Tuition', 'Coaching', 'School', 'Preschool & Daycare',
  'College', 'Computer Classes', 'Coding Classes', 'Spoken English',
  'Competitive Exams', 'Abacus', 'Music Classes', 'Dance Classes',
  'Art Classes', 'Singing Classes', 'Swimming Classes',
  'Karate & Self Defence', 'Sports Coaching', 'Cricket Academy', 'Library',
  'Photography', 'Videography', 'Wedding Photography', 'Photo Studio',
  'Video Editor', 'Reel Editor', 'Graphic Designer', 'Web Designer',
  'Website Development', 'App Development', 'IT Services',
  'Digital Marketing', 'Social Media Manager', 'Content Writer', 'Animator',
  'Voice Over', 'Printing Press', 'Flex & Banner Printing',
  'T-Shirt Printing', 'Xerox & Photocopy', 'Cyber Cafe',
  'Event Planner', 'Wedding Planner', 'Wedding Decor', 'Tent House',
  'DJ & Sound', 'Sound System', 'Lighting & Decoration', 'Mehndi',
  'Band Baja', 'Dhol', 'Anchor & Host', 'Birthday Decoration',
  'Balloon Decoration', 'Party Hall', 'Banquet Hall', 'Marriage Garden',
  'Priest & Pandit', 'Astrologer', 'Invitation Cards', 'Choreographer',
  'Accountant', 'CA & Tax', 'GST Services', 'Lawyer', 'Notary',
  'Insurance Agent', 'Loan Agent', 'Real Estate', 'Property Dealer',
  'Broker', 'Builder', 'Travel Agency', 'Tours & Travels', 'Visa & Passport',
  'Ticket Booking', 'Money Transfer', 'Aadhaar & CSC Services',
  'Typing & Documentation', 'Job Placement', 'Marketing Agency',
  'Tailor', 'Ladies Tailor', 'Embroidery', 'Shoe Repair', 'Watch Repair',
  'Mobile Repair', 'Laptop Repair', 'Key Maker',
  'Hotel', 'Hostel', 'PG & Hostel', 'Lodge', 'Guest House', 'Homestay',
  'Resort', 'Farmhouse', 'Coworking Space',
  'Flats & Rooms', 'Shop for Rent', 'Office Space', 'Car Rental',
  'Bike Rental', 'Cycle Rental', 'Furniture Rental', 'Appliance Rental',
  'Equipment Rental', 'Machinery Rental', 'Costume Rental', 'Camera Rental',
  'Projector Rental', 'Generator Rental', 'Wedding Car', 'Crane Service',
  'JCB & Earthmovers', 'Tractor Rental', 'Scaffolding',
  'Agriculture', 'Seeds & Fertilizers', 'Pesticides', 'Tractor Repair',
  'Dairy Farm', 'Poultry Farm', 'Rice Mill', 'Oil Mill', 'Ice Factory',
  'Warehouse', 'Cold Storage', 'Wholesale', 'Distributor', 'Manufacturer',
  'Machine Repair', 'Lathe Works', 'Industrial Supplies',
];
